sudo: false
language: python
python:
  - "3.6"
cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TZ=UTC

install:
  - pip install twine
  - pip install --upgrade pip --cache-dir $HOME/.pip-cache/
  - pip install coveralls coverage --cache-dir $HOME/.pip-cache/
  - pip install flake8 --cache-dir $HOME/.pip-cache/
  - pip install -r requirements-dev.txt --cache-dir $HOME/.pip-cache/
  - pip install -e . --cache-dir $HOME/.pip-cache/
script:
  - flake8 molo
  - molo scaffold testapp --require molo.forms --include molo.forms ^forms/
  - cp local_test_settings.py testapp/testapp/settings/local.py
  - mkdir testapp/testapp/templates/
  - mkdir testapp/testapp/templates/core
  - cp molo/forms/test_templates/*.html testapp/testapp/templates/core/
  - cp molo/forms/test_templates/base.html testapp/testapp/templates/base.html
  - flake8 testapp
  - pip install -e testapp
  - py.test --cov=molo.forms --cov-report=term

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Praekelt
  password:
    secure: "X7/cvR9N21Q5XpmKy4HxQ2YvgiiorvsqaU6cBY0e4L/PRGCwFWbBZB27wfxKZhzLnjoir0l0zcxPRJsuUBFJXZ3LprSDsCNi5W68sm74lVvnWLtUxJb+h4i7Ho5RiB41UUbE9yXpRJvW75WMnJPGS/CWjApauQeBDioXrW3WJiPI4f5GWrhUSo3tudI0cHcKsV3vS9dZC39W56fS3leGb/OnRWzu7diE82BWAB45jxwbBlPjmU9drDUVF/nWUE4tKaXuyGgrtd74mLy5StzQo4ND9AFoZ3RCDMmfqqKzcj7vQjyg+Ot3m9M0F/i66mAOhg2c9p2Z6+0yv7ThzxhdKyKaffYWtw1HSzRY3reunBTe2kyDorsSCJGqpLR75/No3eKi360Y5w7fIsKhK2okVAC3uprZ08itiNpo6FEYwmjSOKZZYhin2QiFWlMx+tMhT0CAg++9Y8n/yPAduJON0JtC20w5GWvSyjUzQHkzmHyPsq+Xh0xHKAip9ylsVUU3HUHLqXnNAA/k4Fl1W3h5VucNjdufV6T1kYTFNecHzt6h0oME1dcxW6sUDknc6IZM644VVaHRqkpKXL1QBAwqL3DaMCJnRrFkF66qZc4xbsfaIZWh1c/2516ObzI68YE0ga9ykI8vs53s1GjLHK9/pLCW1ku8DgyMnGDjQEdAHJs="
  on:
    tags: true
    python: 3.6
