sudo: false
language: python
python:
  - "3.6"
cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TZ=UTC

install:
  - pip install twine
  - pip install --upgrade pip --cache-dir $HOME/.pip-cache/
  - pip install coveralls coverage --cache-dir $HOME/.pip-cache/
  - pip install flake8 --cache-dir $HOME/.pip-cache/
  - pip install -r requirements-dev.txt --cache-dir $HOME/.pip-cache/
  - pip install -e . --cache-dir $HOME/.pip-cache/
script:
  - flake8 molo
  - molo scaffold testapp --require molo.forms --include molo.forms ^forms/
  - cp local_test_settings.py testapp/testapp/settings/local.py
  - mkdir testapp/testapp/templates/
  - mkdir testapp/testapp/templates/core
  - cp -a molo/forms/templates/ testapp/testapp/templates/
  - cp molo/forms/test_templates/*.html testapp/testapp/templates/core/
  - cp molo/forms/test_templates/base.html testapp/testapp/templates/base.html
  - flake8 testapp
  - pip install -e testapp
  - py.test --cov=molo.forms --cov-report=term

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: praekelt.org
  password:
    secure: "kMC6AOcqQSVF+B4NsMMHqLTDSK1aagYPPQyiJdiPSiqhE8Q584XcyESkvbq80KFqr8gs4iAMMJPn96ezticNVk3qwv23anYXR9QXitZuIq2e1DEbbw/hIkSX2cnUrBcP7kiF3Uh3SCdt2dxHCXGNiGklZelTFbKuxaWiHeH9hvOHl4dtDckldj8BM5OtzF9zGMnfmcnfQIcBGvwxOOIgEYtmhybpJLSdsgv6hz+3iSGTIg//GkYzYuNw1YvfdT6h82SRQ8ZIdl/92KxGZtTNbdHA10jRgGGfylRyS6Sdfve5ml56nzelxsdagN8hpxz4m8pIDO7GN1gO0Su4w+Fk7B6AY2mGkYtysphVMzIguUrHbm+NlC4As1ie2Qf9y8+TzhNbtImFpHdgO3KErzg1otOjfkDSTOnPfdrqMmcUFq5exkUvv8VZ/zd9iYliflj0ux3XHa3PNE39u2l8MV9yqBpI2vT5n8sYT+dgfJEsrmd9P53XGIA+Tp8bbvdgEQt5j1+LWi5CBU4BNddVfvj/2YVjEscDKOCEZDfJmBNsWGdTcN2TI0DdR+/K4yaRqNsp+C3rW9QTxD7TeisyZMvV6F8F2iiFlvBC6CFy0ngRtjWjHtawaEJuB6iaCOxIhu2ySd+L6L7KQvFLR7K9LyV9pQj/ICHS3U+Y2hKzc7AhPQQ="
  on:
    tags: true
    python: 3.6
