# Generated by Django 3.1.10 on 2021-05-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20210111_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='moloformpage',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moloformpage',
            name='is_winnder',
            field=models.BooleanField(default=False),
        ),
    ]
