# Generated by Django 3.1.10 on 2021-05-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20210511_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moloformpage',
            name='is_shortlisted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='moloformpage',
            name='is_winnder',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
