# Generated by Django 3.1.10 on 2021-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_auto_20210511_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moloformpage',
            name='is_shortlisted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='moloformpage',
            name='is_winnder',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
