# Generated by Django 3.1.10 on 2021-05-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_auto_20210511_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moloformpage',
            name='is_shortlisted',
        ),
        migrations.RemoveField(
            model_name='moloformpage',
            name='is_winnder',
        ),
        migrations.AddField(
            model_name='moloformsubmission',
            name='is_shortlisted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='moloformsubmission',
            name='is_winnder',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
